/**
 * This is a simplified placeholder for the PDF.js library
 * In a real application, you would include the actual PDF.js library
 * which can be downloaded from https://mozilla.github.io/pdf.js/
 */

// Create a global pdfjsLib object
window.pdfjsLib = {
    // Mock getDocument function
    getDocument: function(data) {
        const loadingTask = {
            onProgress: null,
            promise: new Promise((resolve) => {
                // Simulate loading time
                setTimeout(() => {
                    resolve({
                        numPages: 3,
                        getPage: function(pageNum) {
                            return new Promise((resolve) => {
                                setTimeout(() => {
                                    resolve({
                                        getViewport: function({ scale }) {
                                            return {
                                                width: 595 * scale,
                                                height: 842 * scale
                                            };
                                        },
                                        render: function() {
                                            return {
                                                promise: new Promise((resolve) => {
                                                    setTimeout(resolve, 500);
                                                })
                                            };
                                        },
                                        getTextContent: function() {
                                            return new Promise((resolve) => {
                                                setTimeout(() => {
                                                    resolve({
                                                        items: [
                                                            { str: 'This is sample text from page ' + pageNum },
                                                            { str: 'PDF conversion is working!' },
                                                            { str: 'Generated by FileWizard' }
                                                        ]
                                                    });
                                                }, 300);
                                            });
                                        }
                                    });
                                }, 500);
                            });
                        }
                    });
                }, 1000);
            })
        };
        
        // Simulate progress
        setTimeout(() => {
            if (loadingTask.onProgress) {
                loadingTask.onProgress({ loaded: 30, total: 100 });
            }
        }, 300);
        
        setTimeout(() => {
            if (loadingTask.onProgress) {
                loadingTask.onProgress({ loaded: 70, total: 100 });
            }
        }, 600);
        
        setTimeout(() => {
            if (loadingTask.onProgress) {
                loadingTask.onProgress({ loaded: 100, total: 100 });
            }
        }, 900);
        
        return loadingTask;
    },
    
    // Mock GlobalWorkerOptions
    GlobalWorkerOptions: {
        workerSrc: ''
    }
};